name: Build

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        pip install sphinx
    - name: Clone scripts
      uses: actions/checkout@v1
    - name: Set up DFHack
      run: |
        git clone git://github.com/dfhack/dfhack $HOME/dfhack --depth 1 --branch develop
        git -C $HOME/dfhack submodule update --init --depth 1 --remote plugins/stonesense library/xml
        rmdir $HOME/dfhack/scripts
        ln -sv $(pwd) $HOME/dfhack/scripts
    - name: Build docs
      run: |
        sphinx-build -qW -j3 $HOME/dfhack html
    - name: Check for missing docs
      run: python $HOME/dfhack/travis/script-docs.py .
    - name: Upload docs
      if: success() || failure()
      uses: actions/upload-artifact@master
      with:
        name: docs
        path: html
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install lua5.3
    - name: Clone scripts
      uses: actions/checkout@v1
    - name: Set up DFHack
      run: |
        git clone git://github.com/dfhack/dfhack $HOME/dfhack --depth 1 --branch develop
        rmdir $HOME/dfhack/scripts
        ln -sv $(pwd) $HOME/dfhack/scripts
    - name: Check whitespace
      run: python $HOME/dfhack/travis/lint.py
    - name: Check Lua syntax
      if: success() || failure()
      run: python $HOME/dfhack/travis/script-syntax.py --ext=lua --cmd="luac5.3 -p" --github-actions
    - name: Check Ruby syntax
      if: success() || failure()
      run: python $HOME/dfhack/travis/script-syntax.py --ext=rb --cmd="ruby -c" --github-actions
